import { TypeBold } from "react-bootstrap-icons";

export const toolbar = {
  options: [
    "inline",
    "blockType",
    "fontSize",
    "fontFamily",
    "list",
    "textAlign",
    "colorPicker",
    "link",
    "emoji",
    "remove",
    "history",
  ],
  inline: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: [
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "monospace",
    ],
    bold: {
      icon: "./text-editor-svgs/type-bold.svg",
      className: undefined,
    },
    italic: {
      icon: "./text-editor-svgs/italic.svg",
      className: undefined,
    },
    underline: {
      icon: "./text-editor-svgs/underline.svg",
      className: undefined,
    },
    strikethrough: {
      icon: "./text-editor-svgs/strikethrough.svg",
      className: undefined,
    },
    monospace: {
      icon: "./text-editor-svgs/code.svg",
      className: undefined,
    },
    // superscript: { icon: superscript, className: undefined },
    // subscript: { icon: subscript, className: undefined },
  },
  //   blockType: {
  //     inDropdown: true,
  //     options: ['Normal', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Blockquote', 'Code'],
  //     className: undefined,
  //     component: undefined,
  //     dropdownClassName: undefined,
  //   },
    fontSize: {
      icon: undefined,
      options: [8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72, 96],
    //   className: undefined,
    //   component: undefined,
    //   dropdownClassName: undefined,
    },
  //   fontFamily: {
  //     options: ['Arial', 'Georgia', 'Impact', 'Tahoma', 'Times New Roman', 'Verdana'],
  //     className: undefined,
  //     component: undefined,
  //     dropdownClassName: undefined,
  //   },
  list: {
    //     inDropdown: false,
    //     className: undefined,
    //     component: undefined,
    //     dropdownClassName: undefined,
    options: ["unordered", "ordered", "indent", "outdent"],
    unordered: {
      icon: "./text-editor-svgs/list-ul.svg",
      className: undefined,
    },
    ordered: {
      icon: "./text-editor-svgs/list-ol.svg",
      className: undefined,
    },
    indent: {
      icon: "./text-editor-svgs/indent-left.svg",
      className: undefined,
    },
    outdent: {
      icon: "./text-editor-svgs/indent-right.svg",
      className: undefined,
    },
  },
    textAlign: {
  //     inDropdown: false,
  //     className: undefined,
  //     component: undefined,
  //     dropdownClassName: undefined,
      options: ['left', 'center', 'right', 'justify'],
      left: { icon: "./text-editor-svgs/text-left.svg", className: undefined },
      center: { icon: "./text-editor-svgs/text-center.svg", className: undefined },
      right: { icon: "./text-editor-svgs/text-right.svg", className: undefined },
      justify: { icon: "./text-editor-svgs/text-justify.svg", className: undefined },
    },
    colorPicker: {
      icon: "./text-editor-svgs/color-picker.svg",
      className: undefined,
      component: undefined,
      popupClassName: undefined,
      colors: ['rgb(97,189,109)', 'rgb(26,188,156)', 'rgb(84,172,210)', 'rgb(44,130,201)',
        'rgb(147,101,184)', 'rgb(71,85,119)', 'rgb(204,204,204)', 'rgb(65,168,95)', 'rgb(0,168,133)',
        'rgb(61,142,185)', 'rgb(41,105,176)', 'rgb(85,57,130)', 'rgb(40,50,78)', 'rgb(0,0,0)',
        'rgb(247,218,100)', 'rgb(251,160,38)', 'rgb(235,107,86)', 'rgb(226,80,65)', 'rgb(163,143,132)',
        'rgb(239,239,239)', 'rgb(255,255,255)', 'rgb(250,197,28)', 'rgb(243,121,52)', 'rgb(209,72,65)',
        'rgb(184,49,47)', 'rgb(124,112,107)', 'rgb(209,213,216)'],
    },
    link: {
      inDropdown: false,
      className: undefined,
      component: undefined,
      popupClassName: undefined,
      dropdownClassName: undefined,
      showOpenOptionOnHover: true,
      defaultTargetOption: '_self',
      options: ['link'],
      link: { icon: "./text-editor-svgs/link.svg", className: undefined },
      linkCallback: undefined
    },
    emoji: {
      icon: "./text-editor-svgs/emoji.svg",
      className: undefined,
      component: undefined,
      popupClassName: undefined,
      emojis: [
        '😀', '😁', '😂', '😃', '😉', '😋', '😎', '😍', '😗', '🤗', '🤔', '😣', '😫', '😴', '😌', '🤓',
        '😛', '😜', '😠', '😇', '😷', '😈', '👻', '😺', '😸', '😹', '😻', '😼', '😽', '🙀', '🙈',
        '🙉', '🙊', '👼', '👮', '🕵', '💂', '👳', '🎅', '👸', '👰', '👲', '🙍', '🙇', '🚶', '🏃', '💃',
        '⛷', '🏂', '🏌', '🏄', '🚣', '🏊', '⛹', '🏋', '🚴', '👫', '💪', '👈', '👉', '👉', '👆', '🖕',
        '👇', '🖖', '🤘', '🖐', '👌', '👍', '👎', '✊', '👊', '👏', '🙌', '🙏', '🐵', '🐶', '🐇', '🐥',
        '🐸', '🐌', '🐛', '🐜', '🐝', '🍉', '🍄', '🍔', '🍤', '🍨', '🍪', '🎂', '🍰', '🍾', '🍷', '🍸',
        '🍺', '🌍', '🚑', '⏰', '🌙', '🌝', '🌞', '⭐', '🌟', '🌠', '🌨', '🌩', '⛄', '🔥', '🎄', '🎈',
        '🎉', '🎊', '🎁', '🎗', '🏀', '🏈', '🎲', '🔇', '🔈', '📣', '🔔', '🎵', '🎷', '💰', '🖊', '📅',
        '✅', '❎', '💯',
      ],
    },
    // embedded: {
    //   icon: embedded,
    //   className: undefined,
    //   component: undefined,
    //   popupClassName: undefined,
    //   embedCallback: undefined,
    //   defaultSize: {
    //     height: 'auto',
    //     width: 'auto',
    //   },
    // },
    remove: { icon: "./text-editor-svgs/remove.svg", className: undefined, component: undefined },
    history: {
      inDropdown: false,
      className: undefined,
      component: undefined,
      dropdownClassName: undefined,
      options: ['undo', 'redo'],
      undo: { icon: "./text-editor-svgs/undo.svg", className: undefined },
      redo: { icon: "./text-editor-svgs/redo.svg", className: undefined },
    },
};
